#!/usr/bin/python3
one, two = 0, 0
answer = 0
numbers = ()
for i in range(len(numbers)):
    for j in range(2, numbers[i]):

        if (numbers[i] % j == 0):
            one = j
            two = range(2, (numbers[i] - 1))
            answer = numbers[i]
            for k in two:
                if one * k == answer:
                    print("{} = {} * {}".format(numbers[i], one, k))
                break
